name: Basic CI pipeline

on: [push]
jobs: 
    builds:
        runs-on: ubuntu-latest

        steps:
            - name: Build Stage
              run: echo "hello from Ci"
            - name: Test Stage
              run: echo "test cases passed"
            - name: Build deploy
              run: echo "Applicatin deployed successfully"    